### ISSUE TITLE
Does not work with intranet web sites that serves through a DNS name

### ISSUE THREAD

**Issue by beyefendi** [enkomio/Mandolin0#2]
What steps will reproduce the problem?
Mandolin0.exe --template intranet -w http://apply.company/login.aspx

What is the expected output? What do you see instead?
Throws an exception
System.UriFormatException: Invalid URI: The format of the URI cannot be determined

What version of the product are you using? On what operating system?
Mandolin00.1.2.2 Mandolin0.exe is running on Windows Server 2012 R2 (64 bit)

**Comment by enkomio** [comment]
Could you post the full stack trace of the error?

**Comment by beyefendi** [comment]
admin      [                                             ]

Unhandled Exception:Unhandled Exception:

Unhandled Exception:Unhandled Exception:

Unhandled Exception:

Unhandled Exception:Unhandled Exception:

Unhandled Exception:Unhandled Exception:Unhandled Exception:
Unhandled Exception:Unhandled Exception:Unhandled Exception:Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.NotSupportedException: The URI prefix is not recogni
zed.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.NotSupportedExceptio
n: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.NotSupportedExceptio
n: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

System.NotSupportedException: The URI prefix is not recognized.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.NotSupportedException: The URI prefix is not recogni
zed.
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1192-1.Invoke(Exceptio
n e)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction
)
   at <StartupCode$FSharp-Core>.$Control.-ctor@476-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

## 

Sorry for the late response, it is hard to take data from intranet to internet for us.
